import type { Dashboard, Notification, Project, SearchResults, Story, Task, User, WorkStatus } from '../types';
const base = '/api';
const tokenKey = 'agileflow.token';
export class ApiError extends Error { constructor(message: string, public status: number, public code?: string) { super(message); } }
export const authStore = { get: () => sessionStorage.getItem(tokenKey), set: (token: string) => sessionStorage.setItem(tokenKey, token), clear: () => sessionStorage.removeItem(tokenKey) };
async function request<T>(path: string, options?: RequestInit): Promise<T> { const token = authStore.get(); const response = await fetch(`${base}${path}`, { headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options?.headers }, ...options }); const text = await response.text(); let payload: { data?: T; error?: { message?: string; code?: string } } | null = null; try { payload = text ? JSON.parse(text) as { data?: T; error?: { message?: string; code?: string } } : null; } catch { /* unexpected non-JSON response uses the generic API error below */ } if (!response.ok) throw new ApiError(payload?.error?.message ?? 'Unable to complete the request.', response.status, payload?.error?.code); return payload?.data as T; }
type Credentials = { email: string; password: string };
type AuthResult = { token: string; user: User };
export const api = {
  login: (data: Credentials) => request<AuthResult>('/auth/login', { method: 'POST', body: JSON.stringify(data) }), register: (data: Credentials & { name: string }) => request<AuthResult>('/auth/register', { method: 'POST', body: JSON.stringify(data) }), logout: () => request<void>('/auth/logout', { method: 'POST' }), me: () => request<User>('/auth/me'),
  projects: () => request<Project[]>('/projects'), project: (id: string) => request<Project>(`/projects/${id}`), createProject: (data: Partial<Project>) => request<Project>('/projects', { method: 'POST', body: JSON.stringify(data) }), updateProject: (id: string, data: Partial<Project>) => request<Project>(`/projects/${id}`, { method: 'PUT', body: JSON.stringify(data) }), deleteProject: (id: string) => request<void>(`/projects/${id}`, { method: 'DELETE' }),
  users: () => request<User[]>('/users'), projectMembers: (projectId: string) => request<User[]>(`/projects/${projectId}/members`), addProjectMember: (projectId: string, userId: string) => request<void>(`/projects/${projectId}/members`, { method: 'POST', body: JSON.stringify({ userId }) }), createStory: (projectId: string, data: Partial<Story> & { allowSimilar?: boolean }) => request<Story>(`/projects/${projectId}/stories`, { method: 'POST', body: JSON.stringify(data) }), updateStory: (id: string, data: Partial<Story>) => request<Story>(`/stories/${id}`, { method: 'PUT', body: JSON.stringify(data) }), deleteStory: (id: string) => request<void>(`/stories/${id}`, { method: 'DELETE' }),
  tasks: (filters = '') => request<Task[]>(`/tasks${filters ? `?${filters}` : ''}`), createTask: (storyId: string, data: Partial<Task>) => request<Task>(`/stories/${storyId}/tasks`, { method: 'POST', body: JSON.stringify(data) }), updateTask: (id: string, data: Partial<Task>) => request<Task>(`/tasks/${id}`, { method: 'PUT', body: JSON.stringify(data) }), deleteTask: (id: string) => request<void>(`/tasks/${id}`, { method: 'DELETE' }),
  notifications: () => request<Notification[]>('/notifications'), readNotification: (id: string) => request<Notification>(`/notifications/${id}/read`, { method: 'PUT' }), readAllNotifications: () => request<void>('/notifications/read-all', { method: 'PUT' }), dashboard: () => request<Dashboard>('/dashboard'), search: (query: string) => request<SearchResults>(`/search?q=${encodeURIComponent(query)}`), kanban: (projectId?: string) => request<Record<WorkStatus, Task[]>>(`/kanban${projectId ? `?projectId=${projectId}` : ''}`)
};
