import { JobStatus, Role } from '@prisma/client';
import { beforeEach, describe, expect, it } from 'vitest';
import request from 'supertest';
import { createApp } from './app.js';
import { hashPassword } from './auth.js';
import { prisma } from './db.js';
import { processNextJob, recoverStaleJobs } from './services/jobService.js';

const app = createApp();
async function user(role: Role, email = `${role.toLowerCase()}-${Math.random()}@test.dev`) { return prisma.user.create({ data: { name: role, email, role, passwordHash: await hashPassword('Password123!') } }); }
async function login(account: { email: string }) { const response = await request(app).post('/api/auth/login').send({ email: account.email, password: 'Password123!' }).expect(200); return `Bearer ${response.body.data.token}`; }
async function actor(role: Role) { const account = await user(role); return { account, authorization: await login(account) }; }
async function project(authorization: string, key = `T${Math.random().toString(36).slice(2, 7).toUpperCase()}`) { return (await request(app).post('/api/projects').set('Authorization', authorization).send({ key, name: 'Test Project' }).expect(201)).body.data; }

beforeEach(async () => { await prisma.backgroundJob.deleteMany(); await prisma.notification.deleteMany(); await prisma.activity.deleteMany(); await prisma.task.deleteMany(); await prisma.userStory.deleteMany(); await prisma.projectMember.deleteMany(); await prisma.project.deleteMany(); await prisma.user.deleteMany(); });

describe('authentication', () => {
  it('registers safely, validates credentials, protects routes, and invalidates a logged-out token', async () => { await request(app).get('/api/projects').expect(401); const registered = await request(app).post('/api/auth/register').send({ name: 'New Member', email: 'new@test.dev', password: 'Password123!' }).expect(201); expect(registered.body.data.user.passwordHash).toBeUndefined(); await request(app).post('/api/auth/register').send({ name: 'New Member', email: 'new@test.dev', password: 'Password123!' }).expect(409); await request(app).post('/api/auth/login').send({ email: 'new@test.dev', password: 'wrong' }).expect(401); const authorization = `Bearer ${registered.body.data.token}`; await request(app).get('/api/auth/me').set('Authorization', authorization).expect(200); await request(app).post('/api/auth/logout').set('Authorization', authorization).expect(204); await request(app).get('/api/auth/me').set('Authorization', authorization).expect(401); });
});

describe('authorization and project membership', () => {
  it('enforces manager/admin actions and hides non-member project data', async () => { const manager = await actor(Role.MANAGER); const member = await actor(Role.MEMBER); const admin = await actor(Role.ADMIN); const created = await project(manager.authorization, 'SCOPE'); await request(app).get('/api/projects').set('Authorization', member.authorization).expect(({ body }) => expect(body.data).toHaveLength(0)); await request(app).get(`/api/projects/${created.id}`).set('Authorization', member.authorization).expect(403); await request(app).post('/api/projects').set('Authorization', member.authorization).send({ key: 'NOPE', name: 'Nope' }).expect(403); await request(app).delete(`/api/projects/${created.id}`).set('Authorization', manager.authorization).expect(403); await request(app).post(`/api/projects/${created.id}/members`).set('Authorization', manager.authorization).send({ userId: member.account.id }).expect(201); await request(app).get(`/api/projects/${created.id}`).set('Authorization', member.authorization).expect(200); await request(app).delete(`/api/projects/${created.id}`).set('Authorization', admin.authorization).expect(204); });
});

describe('keys, validation and hierarchy', () => {
  it('generates keys, rejects duplicates, and validates task filter values', async () => { const manager = await actor(Role.MANAGER); const item = await project(manager.authorization, 'ECOM'); await request(app).post('/api/projects').set('Authorization', manager.authorization).send({ key: 'ECOM', name: 'Duplicate' }).expect(409); const story = (await request(app).post(`/api/projects/${item.id}/stories`).set('Authorization', manager.authorization).send({ title: 'Customer Registration' }).expect(201)).body.data; expect(story.key).toBe('ECOM-US-001'); await request(app).post(`/api/projects/${item.id}/stories`).set('Authorization', manager.authorization).send({ title: ' customer   registration ' }).expect(409); const task = (await request(app).post(`/api/stories/${story.id}/tasks`).set('Authorization', manager.authorization).send({ title: 'Build registration form' }).expect(201)).body.data; expect(task.key).toBe('ECOM-T-001'); await request(app).get(`/api/stories/${story.id}/tasks?status=NOT_A_STATUS`).set('Authorization', manager.authorization).expect(400); await request(app).post('/api/stories/not-real/tasks').set('Authorization', manager.authorization).send({ title: 'Nope' }).expect(404); });
  it('allows members to update only status on their own assigned tasks', async () => { const manager = await actor(Role.MANAGER); const member = await actor(Role.MEMBER); const item = await project(manager.authorization); await request(app).post(`/api/projects/${item.id}/members`).set('Authorization', manager.authorization).send({ userId: member.account.id }).expect(201); const story = (await request(app).post(`/api/projects/${item.id}/stories`).set('Authorization', manager.authorization).send({ title: 'A story' })).body.data; const task = (await request(app).post(`/api/stories/${story.id}/tasks`).set('Authorization', manager.authorization).send({ title: 'My task', assignedToId: member.account.id, dueDate: '2030-01-01' })).body.data; await request(app).put(`/api/tasks/${task.id}`).set('Authorization', member.authorization).send({ key: task.key, title: task.title, description: task.description, priority: task.priority, status: 'DONE', assignedToId: member.account.id, dueDate: '2030-01-01' }).expect(200); await request(app).put(`/api/tasks/${task.id}`).set('Authorization', member.authorization).send({ key: task.key, title: task.title, description: task.description, priority: task.priority, status: 'DONE', assignedToId: member.account.id, dueDate: '2031-01-01' }).expect(403); });
});

describe('dashboard, search, notifications and jobs', () => {
  it('uses only accessible data and creates one notification per durable assignment job', async () => { const manager = await actor(Role.MANAGER); const assignee = await actor(Role.MEMBER); const item = await project(manager.authorization, 'FIND'); await request(app).post(`/api/projects/${item.id}/members`).set('Authorization', manager.authorization).send({ userId: assignee.account.id }).expect(201); const story = (await request(app).post(`/api/projects/${item.id}/stories`).set('Authorization', manager.authorization).send({ title: 'Search registration' })).body.data; const task = (await request(app).post(`/api/stories/${story.id}/tasks`).set('Authorization', manager.authorization).send({ title: 'Registration API', assignedToId: assignee.account.id, status: 'TODO' })).body.data; const metrics = await request(app).get('/api/dashboard').set('Authorization', assignee.authorization).expect(200); expect(metrics.body.data.totals.tasks).toBe(1); const search = await request(app).get('/api/search?q=registration').set('Authorization', assignee.authorization).expect(200); expect(search.body.data.tasks[0].key).toBe(task.key); const job = await prisma.backgroundJob.findFirstOrThrow({ where: { status: JobStatus.PENDING } }); await processNextJob(); await processNextJob(); expect(await prisma.notification.count({ where: { sourceJobId: job.id } })).toBe(1); });
  it('retries failures and recovers stale claimed jobs', async () => { const job = await prisma.backgroundJob.create({ data: { type: 'UNKNOWN', payload: '{}' } }); for (let i = 0; i < 3; i++) { await prisma.backgroundJob.update({ where: { id: job.id }, data: { runAfter: new Date() } }); await processNextJob(); } expect((await prisma.backgroundJob.findUnique({ where: { id: job.id } }))?.status).toBe(JobStatus.FAILED); const stuck = await prisma.backgroundJob.create({ data: { type: 'UNKNOWN', payload: '{}', status: JobStatus.PROCESSING, lockedAt: new Date(Date.now() - 120_000) } }); await recoverStaleJobs(60_000); expect((await prisma.backgroundJob.findUnique({ where: { id: stuck.id } }))?.status).toBe(JobStatus.PENDING); });
});
