import { Role, type Prisma, type User } from '@prisma/client';
import { Router } from 'express';
import { allowRoles, managerRoles, publicUser, requireAuth, signToken, verifyPassword, hashPassword } from './auth.js';
import { prisma } from './db.js';
import { asyncHandler, AppError, notFound } from './errors.js';
import { loginRateLimit } from './services/loginRateLimit.js';
import { createActivity } from './services/activityService.js';
import { adminUserInput, loginInput, passwordInput, projectInput, registerInput, storyInput, taskFilters, taskInput } from './validators.js';

const id = (value: string | string[]) => Array.isArray(value) ? value[0] : value;
const taskInclude = { assignedTo: { select: { id: true, name: true, email: true, role: true } } } as const;
const storyInclude = { tasks: { include: taskInclude, orderBy: { createdAt: 'asc' as const } } } as const;
const summary = (project: { stories: Array<{ tasks: Array<{ status: string }> }> }) => { const tasks = project.stories.flatMap(story => story.tasks); const statusCounts = { todo: tasks.filter(t => t.status === 'TODO').length, inProgress: tasks.filter(t => t.status === 'IN_PROGRESS').length, done: tasks.filter(t => t.status === 'DONE').length }; return { storyCount: project.stories.length, taskCount: tasks.length, completedCount: statusCounts.done, statusCounts, progress: tasks.length ? Math.round(statusCounts.done / tasks.length * 100) : 0 }; };
const scope = (user: User): Prisma.ProjectWhereInput => user.role === Role.ADMIN ? {} : { members: { some: { userId: user.id } } };
const normalize = (value: string) => value.toLowerCase().trim().replace(/\s+/g, ' ');
async function assertProjectAccess(user: User, projectId: string) { const project = await prisma.project.findFirst({ where: { id: projectId, ...scope(user) } }); if (project) return project; if (!await prisma.project.findUnique({ where: { id: projectId } })) throw notFound('Project'); throw new AppError(403, 'PERMISSION_DENIED', "You don't have permission to access this project"); }
async function assertProjectManager(user: User, projectId: string) { const project = await assertProjectAccess(user, projectId); if (!managerRoles.includes(user.role)) throw new AppError(403, 'PERMISSION_DENIED', "You don't have permission to perform this action"); return project; }
async function projectKey(name: string) { const root = (name.match(/[A-Za-z0-9]+/g)?.join('').slice(0, 6).toUpperCase() || 'PROJ'); let key = root; let n = 2; while (await prisma.project.findUnique({ where: { key }, select: { id: true } })) key = `${root.slice(0, 9)}-${n++}`; return key; }
async function workKey(prefix: string, kind: 'US' | 'T') { const base = `${prefix}-${kind}-`; const rows = kind === 'US' ? await prisma.userStory.findMany({ where: { key: { startsWith: base } }, select: { key: true } }) : await prisma.task.findMany({ where: { key: { startsWith: base } }, select: { key: true } }); const nums = rows.map(row => Number(row.key.slice(base.length))).filter(Number.isFinite); return `${base}${String((nums.length ? Math.max(...nums) : 0) + 1).padStart(3, '0')}`; }
async function assertTaskAccess(user: User, taskId: string) { const task = await prisma.task.findUnique({ where: { id: taskId }, include: { userStory: { include: { project: true } } } }); if (!task) throw notFound('Task'); await assertProjectAccess(user, task.userStory.projectId); return task; }

export const api = Router();
api.get('/health', (_req, res) => res.json({ data: { status: 'ok' } }));
api.post('/auth/register', asyncHandler(async (req, res) => { const input = registerInput.parse(req.body); if (await prisma.user.findUnique({ where: { email: input.email } })) throw new AppError(409, 'DUPLICATE_EMAIL', 'An account with this email already exists'); const user = await prisma.user.create({ data: { name: input.name, email: input.email, passwordHash: await hashPassword(input.password), role: Role.MEMBER } }); res.status(201).json({ data: { token: signToken(user), user: publicUser(user) } }); }));
api.post('/auth/login', loginRateLimit, asyncHandler(async (req, res) => { const input = loginInput.parse(req.body); const user = await prisma.user.findUnique({ where: { email: input.email } }); if (!user || !await verifyPassword(input.password, user.passwordHash)) throw new AppError(401, 'INVALID_CREDENTIALS', 'Email or password is incorrect'); res.json({ data: { token: signToken(user), user: publicUser(user) } }); }));

api.use(requireAuth);
api.post('/auth/logout', asyncHandler(async (req, res) => { await prisma.user.update({ where: { id: req.authUser!.id }, data: { sessionVersion: { increment: 1 } } }); res.status(204).send(); }));
api.get('/auth/me', (req, res) => res.json({ data: publicUser(req.authUser!) }));
api.put('/auth/password', asyncHandler(async (req, res) => { const input = passwordInput.parse(req.body); if (!await verifyPassword(input.currentPassword, req.authUser!.passwordHash)) throw new AppError(401, 'INVALID_CREDENTIALS', 'Current password is incorrect'); const user = await prisma.user.update({ where: { id: req.authUser!.id }, data: { passwordHash: await hashPassword(input.newPassword), sessionVersion: { increment: 1 } } }); res.json({ data: { token: signToken(user), user: publicUser(user) } }); }));

api.get('/users', allowRoles(...managerRoles), asyncHandler(async (_req, res) => res.json({ data: (await prisma.user.findMany({ orderBy: { name: 'asc' } })).map(publicUser) })));
api.post('/users', allowRoles(Role.ADMIN), asyncHandler(async (req, res) => { const input = adminUserInput.parse(req.body); const user = await prisma.user.create({ data: { name: input.name, email: input.email, role: input.role ?? Role.MEMBER, passwordHash: await hashPassword(input.password) } }); res.status(201).json({ data: publicUser(user) }); }));
api.put('/users/:id/role', allowRoles(Role.ADMIN), asyncHandler(async (req, res) => { const role = req.body.role as Role; if (!Object.values(Role).includes(role)) throw new AppError(400, 'VALIDATION_ERROR', 'Invalid role'); const user = await prisma.user.findUnique({ where: { id: id(req.params.id) } }); if (!user) throw notFound('User'); res.json({ data: publicUser(await prisma.user.update({ where: { id: user.id }, data: { role, sessionVersion: { increment: 1 } } })) }); }));

api.get('/projects', asyncHandler(async (req, res) => { const projects = await prisma.project.findMany({ where: scope(req.authUser!), include: { stories: { include: { tasks: { select: { status: true } } } } }, orderBy: { updatedAt: 'desc' } }); res.json({ data: projects.map(({ stories, ...project }) => ({ ...project, ...summary({ stories }) })) }); }));
api.post('/projects', allowRoles(...managerRoles), asyncHandler(async (req, res) => { const input = projectInput.parse(req.body); const key = input.key ?? await projectKey(input.name); if (await prisma.project.findUnique({ where: { key } })) throw new AppError(409, 'DUPLICATE_PROJECT_KEY', `A project with key ${key} already exists`); const project = await prisma.$transaction(async tx => { const created = await tx.project.create({ data: { ...input, key } }); await tx.projectMember.create({ data: { projectId: created.id, userId: req.authUser!.id } }); await tx.activity.create({ data: { projectId: created.id, actorId: req.authUser!.id, type: 'PROJECT_CREATED', message: `${req.authUser!.name} created ${created.key}` } }); return created; }); res.status(201).json({ data: project }); }));
api.get('/projects/:id', asyncHandler(async (req, res) => { const allowed = await assertProjectAccess(req.authUser!, id(req.params.id)); const project = await prisma.project.findUnique({ where: { id: allowed.id }, include: { stories: { include: storyInclude, orderBy: { createdAt: 'asc' } }, activities: { orderBy: { createdAt: 'desc' }, take: 12 } } }); if (!project) throw notFound('Project'); const { stories, ...rest } = project; res.json({ data: { ...rest, stories, ...summary({ stories }) } }); }));
api.put('/projects/:id', asyncHandler(async (req, res) => { const project = await assertProjectManager(req.authUser!, id(req.params.id)); const input = projectInput.parse(req.body); if (input.key && input.key !== project.key) { const storyCount = await prisma.userStory.count({ where: { projectId: project.id } }); if (storyCount) throw new AppError(409, 'PROJECT_KEY_LOCKED', 'Project key cannot change after stories have been created'); if (await prisma.project.findUnique({ where: { key: input.key } })) throw new AppError(409, 'DUPLICATE_PROJECT_KEY', `A project with key ${input.key} already exists`); } const updated = await prisma.project.update({ where: { id: project.id }, data: input }); await createActivity(project.id, `${req.authUser!.name} updated ${updated.key}`, 'PROJECT_UPDATED', req.authUser!.id); res.json({ data: updated }); }));
api.delete('/projects/:id', allowRoles(Role.ADMIN), asyncHandler(async (req, res) => { const project = await assertProjectAccess(req.authUser!, id(req.params.id)); await prisma.project.delete({ where: { id: project.id } }); res.status(204).send(); }));
api.get('/projects/:id/members', asyncHandler(async (req, res) => { const project = await assertProjectAccess(req.authUser!, id(req.params.id)); const members = await prisma.projectMember.findMany({ where: { projectId: project.id }, include: { user: true }, orderBy: { user: { name: 'asc' } } }); res.json({ data: members.map(member => publicUser(member.user)) }); }));
api.post('/projects/:id/members', asyncHandler(async (req, res) => { const project = await assertProjectManager(req.authUser!, id(req.params.id)); const userId = String(req.body.userId ?? ''); if (!userId || !await prisma.user.findUnique({ where: { id: userId } })) throw notFound('User'); try { await prisma.projectMember.create({ data: { projectId: project.id, userId } }); } catch { throw new AppError(409, 'DUPLICATE_MEMBERSHIP', 'User is already a project member'); } res.status(201).send(); }));

api.get('/projects/:projectId/stories', asyncHandler(async (req, res) => { const project = await assertProjectAccess(req.authUser!, id(req.params.projectId)); res.json({ data: await prisma.userStory.findMany({ where: { projectId: project.id }, include: storyInclude }) }); }));
api.post('/projects/:projectId/stories', asyncHandler(async (req, res) => { const project = await assertProjectManager(req.authUser!, id(req.params.projectId)); const { allowSimilar, ...input } = storyInput.parse(req.body); const candidates = await prisma.userStory.findMany({ where: { projectId: project.id }, select: { key: true, title: true, status: true } }); const similar = candidates.find(story => normalize(story.title) === normalize(input.title)); if (similar && !allowSimilar) throw new AppError(409, 'SIMILAR_STORY_EXISTS', `Similar user story already exists: ${similar.key} — ${similar.title} (${similar.status})`); const key = input.key ?? await workKey(project.key, 'US'); if (await prisma.userStory.findUnique({ where: { key } })) throw new AppError(409, 'DUPLICATE_STORY_KEY', `A user story with key ${key} already exists`); const story = await prisma.userStory.create({ data: { ...input, key, projectId: project.id } }); await createActivity(project.id, `${req.authUser!.name} created ${story.key}`, 'STORY_CREATED', req.authUser!.id); res.status(201).json({ data: story }); }));
api.get('/stories/:id', asyncHandler(async (req, res) => { const story = await prisma.userStory.findUnique({ where: { id: id(req.params.id) }, include: { ...storyInclude, project: true } }); if (!story) throw notFound('User story'); await assertProjectAccess(req.authUser!, story.projectId); res.json({ data: story }); }));
api.put('/stories/:id', asyncHandler(async (req, res) => { const story = await prisma.userStory.findUnique({ where: { id: id(req.params.id) } }); if (!story) throw notFound('User story'); await assertProjectManager(req.authUser!, story.projectId); const { allowSimilar: _warning, ...input } = storyInput.parse(req.body); if (input.key && input.key !== story.key && await prisma.userStory.findUnique({ where: { key: input.key } })) throw new AppError(409, 'DUPLICATE_STORY_KEY', `A user story with key ${input.key} already exists`); const updated = await prisma.userStory.update({ where: { id: story.id }, data: input }); await createActivity(story.projectId, `${req.authUser!.name} updated ${updated.key}`, 'STORY_UPDATED', req.authUser!.id); res.json({ data: updated }); }));
api.delete('/stories/:id', asyncHandler(async (req, res) => { const story = await prisma.userStory.findUnique({ where: { id: id(req.params.id) } }); if (!story) throw notFound('User story'); await assertProjectManager(req.authUser!, story.projectId); await prisma.userStory.delete({ where: { id: story.id } }); res.status(204).send(); }));

api.get('/stories/:storyId/tasks', asyncHandler(async (req, res) => { const story = await prisma.userStory.findUnique({ where: { id: id(req.params.storyId) } }); if (!story) throw notFound('User story'); await assertProjectAccess(req.authUser!, story.projectId); const filters = taskFilters.parse(req.query); const where: Prisma.TaskWhereInput = { userStoryId: story.id, ...(filters.status ? { status: filters.status } : {}), ...(filters.priority ? { priority: filters.priority } : {}), ...(filters.assignedToId ? { assignedToId: filters.assignedToId } : {}) }; res.json({ data: await prisma.task.findMany({ where, include: taskInclude, orderBy: { dueDate: 'asc' } }) }); }));
api.get('/tasks', asyncHandler(async (req, res) => { const filters = taskFilters.parse(req.query); if (filters.projectId) await assertProjectAccess(req.authUser!, filters.projectId); const where: Prisma.TaskWhereInput = { userStory: { project: scope(req.authUser!) }, ...(filters.projectId ? { userStory: { projectId: filters.projectId } } : {}), ...(filters.storyId ? { userStoryId: filters.storyId } : {}), ...(filters.status ? { status: filters.status } : {}), ...(filters.priority ? { priority: filters.priority } : {}), ...(filters.assignedToId ? { assignedToId: filters.assignedToId } : {}), ...(filters.completed === 'true' ? { status: 'DONE' } : {}), ...(filters.overdue === 'true' ? { dueDate: { lt: new Date() }, status: { not: 'DONE' } } : {}) }; res.json({ data: await prisma.task.findMany({ where, include: { ...taskInclude, userStory: { include: { project: true } } }, orderBy: { dueDate: 'asc' } }) }); }));
api.post('/stories/:storyId/tasks', asyncHandler(async (req, res) => { const story = await prisma.userStory.findUnique({ where: { id: id(req.params.storyId) }, include: { project: true } }); if (!story) throw notFound('User story'); await assertProjectManager(req.authUser!, story.projectId); const input = taskInput.parse(req.body); if (input.assignedToId && !await prisma.projectMember.findUnique({ where: { projectId_userId: { projectId: story.projectId, userId: input.assignedToId } } })) throw new AppError(400, 'ASSIGNEE_NOT_IN_PROJECT', 'Assignee must be a member of this project'); const key = input.key ?? await workKey(story.project.key, 'T'); if (await prisma.task.findUnique({ where: { key } })) throw new AppError(409, 'DUPLICATE_TASK_KEY', `A task with key ${key} already exists`); const task = await prisma.$transaction(async tx => { const created = await tx.task.create({ data: { ...input, key, userStoryId: story.id }, include: taskInclude }); if (created.assignedToId) await tx.backgroundJob.create({ data: { type: 'TASK_ASSIGNED', payload: JSON.stringify({ taskId: created.id, userId: created.assignedToId, assignmentVersion: created.updatedAt.toISOString() }) } }); await tx.activity.create({ data: { projectId: story.projectId, actorId: req.authUser!.id, type: 'TASK_CREATED', message: `${req.authUser!.name} created ${created.key}` } }); return created; }); res.status(201).json({ data: task }); }));
api.get('/tasks/:id', asyncHandler(async (req, res) => { const task = await assertTaskAccess(req.authUser!, id(req.params.id)); const result = await prisma.task.findUnique({ where: { id: task.id }, include: { ...taskInclude, userStory: { include: { project: true } } } }); res.json({ data: result }); }));
api.put('/tasks/:id', asyncHandler(async (req, res) => { const existing = await assertTaskAccess(req.authUser!, id(req.params.id)); const input = taskInput.parse(req.body); const isManager = managerRoles.includes(req.authUser!.role); if (!isManager && existing.assignedToId !== req.authUser!.id) throw new AppError(403, 'PERMISSION_DENIED', "You don't have permission to perform this action"); if (!isManager && (input.title !== existing.title || input.description !== existing.description || input.priority !== existing.priority || input.assignedToId !== existing.assignedToId || input.key !== existing.key || input.dueDate?.getTime() !== existing.dueDate?.getTime())) throw new AppError(403, 'PERMISSION_DENIED', 'Members can only update the status of their assigned tasks'); if (input.assignedToId && !await prisma.projectMember.findUnique({ where: { projectId_userId: { projectId: existing.userStory.projectId, userId: input.assignedToId } } })) throw new AppError(400, 'ASSIGNEE_NOT_IN_PROJECT', 'Assignee must be a member of this project'); if (input.key && input.key !== existing.key && await prisma.task.findUnique({ where: { key: input.key } })) throw new AppError(409, 'DUPLICATE_TASK_KEY', `A task with key ${input.key} already exists`); const task = await prisma.$transaction(async tx => { const updated = await tx.task.update({ where: { id: existing.id }, data: input, include: taskInclude }); if (updated.assignedToId && updated.assignedToId !== existing.assignedToId) await tx.backgroundJob.create({ data: { type: 'TASK_ASSIGNED', payload: JSON.stringify({ taskId: updated.id, userId: updated.assignedToId, assignmentVersion: updated.updatedAt.toISOString() }) } }); if (updated.status !== existing.status) await tx.activity.create({ data: { projectId: existing.userStory.projectId, actorId: req.authUser!.id, type: 'TASK_STATUS_CHANGED', message: `${req.authUser!.name} moved ${updated.key} to ${updated.status.replace('_', ' ')}` } }); return updated; }); res.json({ data: task }); }));
api.delete('/tasks/:id', asyncHandler(async (req, res) => { const task = await assertTaskAccess(req.authUser!, id(req.params.id)); if (!managerRoles.includes(req.authUser!.role)) throw new AppError(403, 'PERMISSION_DENIED', "You don't have permission to perform this action"); await prisma.task.delete({ where: { id: task.id } }); res.status(204).send(); }));

api.get('/notifications', asyncHandler(async (req, res) => { const userId = req.authUser!.role === Role.ADMIN && typeof req.query.userId === 'string' ? req.query.userId : req.authUser!.id; res.json({ data: await prisma.notification.findMany({ where: { userId }, include: { user: { select: { name: true } } }, orderBy: { createdAt: 'desc' } }) }); }));
api.put('/notifications/:id/read', asyncHandler(async (req, res) => { const notification = await prisma.notification.findUnique({ where: { id: id(req.params.id) } }); if (!notification) throw notFound('Notification'); if (notification.userId !== req.authUser!.id && req.authUser!.role !== Role.ADMIN) throw new AppError(403, 'PERMISSION_DENIED', "You don't have permission to perform this action"); res.json({ data: await prisma.notification.update({ where: { id: notification.id }, data: { isRead: true } }) }); }));
api.put('/notifications/read-all', asyncHandler(async (req, res) => { await prisma.notification.updateMany({ where: { userId: req.authUser!.id, isRead: false }, data: { isRead: true } }); res.status(204).send(); }));

api.get('/dashboard', asyncHandler(async (req, res) => { const where = scope(req.authUser!); const [projects, stories, tasks, unread] = await Promise.all([prisma.project.findMany({ where, include: { stories: { include: { tasks: { select: { status: true } } } } } }), prisma.userStory.count({ where: { project: where } }), prisma.task.findMany({ where: { userStory: { project: where } } }), prisma.notification.count({ where: { userId: req.authUser!.id, isRead: false } })]); const status = { TODO: tasks.filter(t => t.status === 'TODO').length, IN_PROGRESS: tasks.filter(t => t.status === 'IN_PROGRESS').length, DONE: tasks.filter(t => t.status === 'DONE').length }; const priority = { LOW: tasks.filter(t => t.priority === 'LOW').length, MEDIUM: tasks.filter(t => t.priority === 'MEDIUM').length, HIGH: tasks.filter(t => t.priority === 'HIGH').length }; res.json({ data: { totals: { projects: projects.length, activeProjects: projects.filter(p => p.status === 'ACTIVE').length, stories, tasks: tasks.length, myTasks: tasks.filter(t => t.assignedToId === req.authUser!.id).length, completedTasks: status.DONE, overdueTasks: tasks.filter(t => !!t.dueDate && t.dueDate < new Date() && t.status !== 'DONE').length, unreadNotifications: unread }, status, priority, projectProgress: projects.map(project => ({ id: project.id, key: project.key, name: project.name, ...summary(project) })) } }); }));
api.get('/search', asyncHandler(async (req, res) => {
  const q = typeof req.query.q === 'string' ? req.query.q.trim() : '';
  if (!q) return res.json({ data: { projects: [], stories: [], tasks: [] } });
  const contains = { contains: q }; const projectScope = scope(req.authUser!);
  const [projects, stories, tasks] = await Promise.all([
    prisma.project.findMany({ where: { AND: [projectScope, { OR: [{ key: contains }, { name: contains }] }] }, take: 10 }),
    prisma.userStory.findMany({ where: { project: projectScope, OR: [{ key: contains }, { title: contains }] }, include: { project: { select: { key: true, name: true } } }, take: 10 }),
    prisma.task.findMany({ where: { userStory: { project: projectScope }, OR: [{ key: contains }, { title: contains }] }, include: { userStory: { include: { project: { select: { key: true, name: true } } } } }, take: 10 })
  ]);
  res.json({ data: { projects, stories, tasks } });
}));
api.get('/kanban', asyncHandler(async (req, res) => { const projectId = typeof req.query.projectId === 'string' ? req.query.projectId : undefined; if (projectId) await assertProjectAccess(req.authUser!, projectId); const tasks = await prisma.task.findMany({ where: { userStory: projectId ? { projectId } : { project: scope(req.authUser!) } }, include: { ...taskInclude, userStory: { include: { project: { select: { id: true, key: true, name: true } } } } }, orderBy: { updatedAt: 'desc' } }); res.json({ data: { TODO: tasks.filter(task => task.status === 'TODO'), IN_PROGRESS: tasks.filter(task => task.status === 'IN_PROGRESS'), DONE: tasks.filter(task => task.status === 'DONE') } }); }));
