import swaggerJSDoc from 'swagger-jsdoc';

const id = { name: 'id', in: 'path', required: true, schema: { type: 'string' } };
export const swaggerSpec = swaggerJSDoc({ definition: { openapi: '3.0.3', info: { title: 'AgileFlow API', version: '2.0.0', description: 'Authenticated REST API for AgileFlow.' }, servers: [{ url: '/api' }], components: { securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'HMAC token' } }, schemas: { Error: { type: 'object', properties: { error: { type: 'object', properties: { code: { type: 'string' }, message: { type: 'string' } } } } }, Login: { type: 'object', required: ['email', 'password'], properties: { email: { type: 'string', format: 'email' }, password: { type: 'string', format: 'password' } } }, Project: { type: 'object', required: ['key', 'name'], properties: { key: { type: 'string', example: 'ECOM' }, name: { type: 'string' }, description: { type: 'string' }, status: { enum: ['ACTIVE', 'COMPLETED', 'ARCHIVED'] } } }, Story: { type: 'object', required: ['title'], properties: { key: { type: 'string', example: 'ECOM-US-001' }, title: { type: 'string' }, description: { type: 'string' }, status: { enum: ['TODO', 'IN_PROGRESS', 'DONE'] }, priority: { enum: ['LOW', 'MEDIUM', 'HIGH'] } } }, Task: { type: 'object', required: ['title'], properties: { key: { type: 'string', example: 'ECOM-T-001' }, title: { type: 'string' }, description: { type: 'string' }, status: { enum: ['TODO', 'IN_PROGRESS', 'DONE'] }, priority: { enum: ['LOW', 'MEDIUM', 'HIGH'] }, assignedToId: { type: 'string', nullable: true }, dueDate: { type: 'string', format: 'date-time', nullable: true } } } } }, paths: {
  '/auth/login': { post: { summary: 'Login', security: [], requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/Login' } } } }, responses: { '200': { description: 'Signed token and safe user' }, '401': { description: 'Invalid credentials' } } } },
  '/auth/register': { post: { summary: 'Register a MEMBER account', security: [], requestBody: { required: true, content: { 'application/json': { schema: { allOf: [{ $ref: '#/components/schemas/Login' }], properties: { name: { type: 'string' } } } } } }, responses: { '201': { description: 'Created' }, '409': { description: 'Duplicate email' } } } },
  '/auth/me': { get: { summary: 'Current user', security: [{ bearerAuth: [] }], responses: { '200': { description: 'Safe user' }, '401': { description: 'Authentication required' } } } },
  '/projects': { get: { summary: 'List projects and live progress', security: [{ bearerAuth: [] }], responses: { '200': { description: 'Projects' } } }, post: { summary: 'Create project (ADMIN/MANAGER)', security: [{ bearerAuth: [] }], requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/Project' } } } }, responses: { '201': { description: 'Created' }, '403': { description: 'Permission denied' }, '409': { description: 'Duplicate key' } } } },
  '/projects/{id}': { get: { summary: 'Project hierarchy, progress and activity', security: [{ bearerAuth: [] }], parameters: [id], responses: { '200': { description: 'Project' }, '404': { description: 'Not found' } } }, put: { summary: 'Update project (ADMIN/MANAGER)', security: [{ bearerAuth: [] }], parameters: [id], requestBody: { content: { 'application/json': { schema: { $ref: '#/components/schemas/Project' } } } }, responses: { '200': { description: 'Updated' } } }, delete: { summary: 'Delete project (ADMIN)', security: [{ bearerAuth: [] }], parameters: [id], responses: { '204': { description: 'Deleted' }, '403': { description: 'Permission denied' } } } },
  '/projects/{projectId}/stories': { post: { summary: 'Create a user story (ADMIN/MANAGER)', security: [{ bearerAuth: [] }], parameters: [{ ...id, name: 'projectId' }], requestBody: { content: { 'application/json': { schema: { $ref: '#/components/schemas/Story' } } } }, responses: { '201': { description: 'Created' }, '409': { description: 'Duplicate key or similar story' } } } },
  '/stories/{storyId}/tasks': { get: { summary: 'List tasks with status/priority/assignee filters', security: [{ bearerAuth: [] }], parameters: [{ ...id, name: 'storyId' }], responses: { '200': { description: 'Tasks' } } }, post: { summary: 'Create task and queue notification (ADMIN/MANAGER)', security: [{ bearerAuth: [] }], parameters: [{ ...id, name: 'storyId' }], requestBody: { content: { 'application/json': { schema: { $ref: '#/components/schemas/Task' } } } }, responses: { '201': { description: 'Created' } } } },
  '/tasks/{id}': { put: { summary: 'Update task; MEMBER may update own status', security: [{ bearerAuth: [] }], parameters: [id], requestBody: { content: { 'application/json': { schema: { $ref: '#/components/schemas/Task' } } } }, responses: { '200': { description: 'Updated' }, '403': { description: 'Permission denied' } } }, delete: { summary: 'Delete task (ADMIN/MANAGER)', security: [{ bearerAuth: [] }], parameters: [id], responses: { '204': { description: 'Deleted' } } } },
  '/notifications': { get: { summary: 'Current user notifications', security: [{ bearerAuth: [] }], responses: { '200': { description: 'Notifications' } } } },
  '/notifications/{id}/read': { put: { summary: 'Mark notification read', security: [{ bearerAuth: [] }], parameters: [id], responses: { '200': { description: 'Updated' } } } },
  '/dashboard': { get: { summary: 'Database-driven dashboard metrics', security: [{ bearerAuth: [] }], responses: { '200': { description: 'Metrics' } } } },
  '/search': { get: { summary: 'Search projects, stories and tasks', security: [{ bearerAuth: [] }], parameters: [{ name: 'q', in: 'query', required: true, schema: { type: 'string' } }], responses: { '200': { description: 'Results' } } } },
  '/kanban': { get: { summary: 'Kanban task columns', security: [{ bearerAuth: [] }], parameters: [{ name: 'projectId', in: 'query', schema: { type: 'string' } }], responses: { '200': { description: 'TODO, IN_PROGRESS and DONE groups' } } } }
} }, apis: [] });
